import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { UserPicker } from './UserPicker.js';
import { DateRangePicker } from './DateRangePicker.js';
import { RepoPicker } from './RepoPicker.js';
import { SessionRestoreBanner } from './SessionRestoreBanner.js';
export function FilterPanel({ selectedUsers, selectedRepoTargets, selectedProjects, startDate, endDate, isLoading, savedSession, onUsersChange, onRepoTargetsChange, onProjectsChange, onStartChange, onEndChange, onPreset, onSubmit, onRestoreSession, onDismissSession, }) {
    const canSubmit = selectedUsers.length > 0 && !isLoading;
    return (_jsxs("aside", { className: "filter-panel", children: [savedSession && (_jsx(SessionRestoreBanner, { session: savedSession, onRestore: onRestoreSession, onDismiss: onDismissSession })), _jsx("h1", { className: "filter-panel__title", children: "Developer Metrics" }), _jsxs("section", { className: "filter-panel__section", children: [_jsx("h2", { className: "filter-panel__section-title", children: "Team members" }), _jsx(UserPicker, { selectedUsers: selectedUsers, onChange: onUsersChange })] }), _jsxs("section", { className: "filter-panel__section", children: [_jsx("h2", { className: "filter-panel__section-title", children: "Projects & Repos" }), _jsx(RepoPicker, { selectedRepoTargets: selectedRepoTargets, selectedProjects: selectedProjects, onRepoTargetsChange: onRepoTargetsChange, onProjectsChange: onProjectsChange })] }), _jsxs("section", { className: "filter-panel__section", children: [_jsx("h2", { className: "filter-panel__section-title", children: "Date range" }), _jsx(DateRangePicker, { startDate: startDate, endDate: endDate, onStartChange: onStartChange, onEndChange: onEndChange, onPreset: onPreset })] }), _jsx("button", { type: "button", className: `btn btn--primary filter-panel__submit${!canSubmit ? ' btn--disabled' : ''}`, disabled: !canSubmit, onClick: onSubmit, "aria-busy": isLoading, children: isLoading ? 'Loading…' : 'Run report' })] }));
}
