import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function SelectionSummary({ selectedUsers, selectedRepoTargets, selectedProjects, startDate, endDate, }) {
    const tier = selectedRepoTargets.length > 0 ? 1 : selectedProjects.length > 0 ? 2 : 3;
    const tierLabel = {
        1: { text: 'Tier 1 — Exact repos', cls: 'summary__tier--1' },
        2: { text: 'Tier 2 — Project-scoped discovery', cls: 'summary__tier--2' },
        3: { text: 'Tier 3 — User profile auto-discover', cls: 'summary__tier--3' },
    }[tier];
    return (_jsxs("div", { className: "summary", children: [_jsxs("div", { className: "summary__header", children: [_jsx("span", { className: "summary__title", children: "Current Selection" }), _jsx("span", { className: `summary__tier ${tierLabel.cls}`, children: tierLabel.text })] }), _jsxs("div", { className: "summary__scroll", children: [_jsxs("div", { className: "summary__group", children: [_jsxs("div", { className: "summary__group-label", children: ["Team members", _jsx("span", { className: "summary__count", children: selectedUsers.length })] }), selectedUsers.length === 0
                                ? _jsx("div", { className: "summary__empty", children: "None selected" })
                                : (_jsx("div", { className: "summary__chips", children: selectedUsers.map((u) => (_jsx("span", { className: "summary__chip summary__chip--user", children: u }, u))) }))] }), tier === 1 && (_jsxs("div", { className: "summary__group", children: [_jsxs("div", { className: "summary__group-label", children: ["Repos (exact)", _jsx("span", { className: "summary__count", children: selectedRepoTargets.length })] }), _jsx("div", { className: "summary__chips", children: selectedRepoTargets.map((t) => {
                                    const key = `${t.projectKey}/${t.repoSlug}`;
                                    return (_jsxs("span", { className: "summary__chip summary__chip--repo", children: [_jsx("span", { className: "summary__chip-project", children: t.projectKey }), _jsx("span", { className: "summary__chip-sep", children: "/" }), t.repoSlug] }, key));
                                }) })] })), tier === 2 && (_jsxs("div", { className: "summary__group", children: [_jsxs("div", { className: "summary__group-label", children: ["Projects", _jsx("span", { className: "summary__count", children: selectedProjects.length })] }), _jsx("div", { className: "summary__chips", children: selectedProjects.map((k) => (_jsx("span", { className: "summary__chip summary__chip--project", children: k }, k))) }), _jsx("div", { className: "summary__note", children: "Repos filtered by user activity in date range" })] })), tier === 3 && (_jsxs("div", { className: "summary__group", children: [_jsx("div", { className: "summary__group-label", children: "Repos" }), _jsx("div", { className: "summary__note", children: "Auto-discovered from user Bitbucket profiles" })] })), _jsxs("div", { className: "summary__group", children: [_jsx("div", { className: "summary__group-label", children: "Date range" }), _jsxs("div", { className: "summary__date-range", children: [_jsx("span", { className: "summary__chip summary__chip--date", children: startDate }), _jsx("span", { className: "summary__date-sep", children: "\u2192" }), _jsx("span", { className: "summary__chip summary__chip--date", children: endDate })] })] })] })] }));
}
